"""empty message

Revision ID: 1367f26b6d21
Revises: a2fccd0ca051
Create Date: 2018-10-31 06:44:09.840814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1367f26b6d21'
down_revision = 'a2fccd0ca051'
branch_labels = None
depends_on = None


 def upgrade():
        # ### commands auto generated by Alembic - please adjust! ###
        op.add_column('users', sa.Column('password', sa.String(length=255)))
        op.execute('UPDATE users SET password=email')
        op.alter_column('users', 'password', nullable=False)
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
